### ISSUE TITLE
fatal error: 'osmium.hpp' file not found

### ISSUE THREAD

**Issue by baditaflorin** [MaZderMind/osm-history-renderer#23]
make
clang++ -g -O3 -Wall -Wextra -pedantic `getconf LFS_CFLAGS` -I/usr/include/postgresql/ -I/usr/include/libxml2/ -DOSMIUM_WITH_GEOS -o osm-history-importer importer.cpp -lexpat -lpq -lproj -lz -lprotobuf-lite -losmpbf -lpthread -lgeos
importer.cpp:17:10: fatal error: 'osmium.hpp' file not found
#include <osmium.hpp>
         ^
1 error generated.
Makefile:39: recipe for target 'osm-history-importer' failed
make: *** [osm-history-importer] Error 1

Trying to compile on Ubuntu 16.04
